### ISSUE TITLE
How do I add/change themes?

### ISSUE THREAD

**Issue by blaasvaer** [documentationjs/documentation-theme-serif#5]
Hi,
How do I add or change themes for documentation (or gulp-documentation)?

**Comment by mocon** [comment]
I would also like to know how to do this. I made a copy of the `default_theme` directory and modified the templates. However, it doesn't seem to load my new theme unless I leave it in `node_modules/documentation` next to the default theme.

I have been unable to find any documentation about this. Can someone point me in the right direction? Thanks.

**Comment by JessicaSachs** [comment]
@mocon I found [these instructions](https://github.com/documentationjs/documentation/blob/master/docs/THEMING.md#customizing-the-default-theme) from documentationjs, hope this helps!

Seems you can just pass in an option to documentationjs on the cli: ```--theme node_modules/documentation-theme-serif```
